#!/usr/bin/env python3
"""Generate _data/older_conferences.yml for the hub's "Older Conferences" section
from the erlang-factory.com census (migration-data/erlang_factory.json).

Per the migration decision, all pre-Sonata editions (Erlang Factory, Erlang User
Conference, Erlang & Elixir Factory Lite) render in ONE separate section at the
end of /conferences/, not under the modern brand sections. Data-driven (a YAML
list) rather than 59 sparse tile files, because most editions have thin data
(some wayback-only, some no confirmed month/city).

The two modern Code BEAM entries in the census (SF 2018, STO 2018) are excluded
here — they belong to code-beam-america / code-beam-stockholm.

Re-run:  python3 migration-data/build_older_conferences.py
"""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "migration-data" / "erlang_factory.json"
OUT = ROOT / "_data" / "older_conferences.yml"


def sub_brand(e):
    n = ((e.get("name") or "") + " " + (e.get("url") or "")).lower()
    if "code beam" in n or "codebeam" in n:
        return None  # modern brand, handled in its own repo
    if "user conference" in n or "/euc" in n or "euc2" in n:
        return "Erlang User Conference"
    if "lite" in n:
        return "Erlang & Elixir Factory Lite"
    if "factory" in n or "sfbay" in n or "/london20" in n:
        return "Erlang Factory"
    return "Other"

# Fixed display order of sub-brands
ORDER = ["Erlang Factory", "Erlang User Conference",
         "Erlang & Elixir Factory Lite", "Other"]


def edition_label(e):
    """Single clean display label. Names usually already include city+year, so
    only append the year when it's not already in the name; construct from
    city+year when there's no name at all (wayback-only editions)."""
    name = (e.get("name") or "").strip()
    year = e.get("year")
    city = (e.get("city") or "").strip()
    if name:
        if year and str(year) not in name:
            return f"{name} ({year})"
        return name
    parts = [p for p in (city, str(year) if year else "") if p]
    return " ".join(parts) if parts else "Erlang Factory edition"


def yaml_escape(s):
    if s is None:
        return None
    s = str(s).replace('"', '\\"')
    return f'"{s}"'


def main():
    data = json.load(open(SRC))
    groups = {b: [] for b in ORDER}
    for e in data:
        b = sub_brand(e)
        if b is None:
            continue
        groups[b].append(e)

    lines = ["# Generated by migration-data/build_older_conferences.py — do not edit by hand.",
             "# Pre-Sonata conference editions (erlang-factory.com era) for the",
             "# 'Older Conferences' section of /conferences/.", ""]
    total = 0
    for b in ORDER:
        editions = groups[b]
        if not editions:
            continue
        # newest first; null year sorts last
        editions.sort(key=lambda e: (-(e.get("year") or 0), (e.get("name") or "")))
        lines.append(f"- brand: {yaml_escape(b)}")
        lines.append("  editions:")
        for e in editions:
            total += 1
            lines.append(f"    - label: {yaml_escape(edition_label(e))}")
            lines.append(f"      url: {yaml_escape(e.get('url'))}")
        lines.append("")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", "utf-8")
    print(f"wrote {OUT} — {total} editions across "
          f"{sum(1 for b in ORDER if groups[b])} sub-brands")
    for b in ORDER:
        if groups[b]:
            print(f"  {b}: {len(groups[b])}")


if __name__ == "__main__":
    main()
