#!/usr/bin/env python3
"""Generate _data/older_conferences.yml for the hub's "Older Conferences" section
from the erlang-factory.com census (migration-data/erlang_factory.json).

Per the migration decision, all pre-Sonata editions (Erlang Factory, Erlang User
Conference, Erlang & Elixir Factory Lite) render in ONE separate section at the
end of /conferences/, not under the modern brand sections. Data-driven (a YAML
list) rather than 59 sparse tile files, because most editions have thin data
(some wayback-only, some no confirmed month/city).

The two modern Code BEAM entries in the census (SF 2018, STO 2018) are excluded
here — they belong to code-beam-america / code-beam-stockholm.

Re-run:  python3 migration-data/build_older_conferences.py
"""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "migration-data" / "erlang_factory.json"
OUT = ROOT / "_data" / "older_conferences.yml"


def sub_brand(e):
    n = ((e.get("name") or "") + " " + (e.get("url") or "")).lower()
    city = (e.get("city") or "").lower()
    if "code beam" in n or "codebeam" in n:
        return None  # modern brand, handled in its own repo
    if "user conference" in n or "/euc" in n or "euc2" in n:
        return "Erlang User Conference"
    if "lite" in n:
        return "Erlang & Elixir Factory Lite"
    # Erlang Factory proper ran ONLY in the San Francisco Bay Area and London;
    # every other city in this era was an Erlang (& Elixir) Factory Lite.
    if ("san francisco" in city or "sfbay" in n
            or city == "london" or "/london20" in n or "/london2" in n):
        return "Erlang Factory"
    return "Erlang & Elixir Factory Lite"

# Fixed display order of sub-brands
ORDER = ["Erlang Factory", "Erlang User Conference",
         "Erlang & Elixir Factory Lite"]


def edition_label(e, brand=None):
    """Single clean display label. For the Lite section, non-Lite-named city
    editions are reformatted to the standard "<City> Erlang Factory Lite
    <year>"; named workshops keep their own name. Otherwise use the existing
    name (appending the year if missing) or build one from city + year."""
    name = (e.get("name") or "").strip()
    year = e.get("year")
    city = (e.get("city") or "").strip()
    if (brand == "Erlang & Elixir Factory Lite" and city
            and "lite" not in name.lower() and "workshop" not in name.lower()):
        return f"{city} Erlang Factory Lite {year}".strip()
    if brand == "Erlang Factory" and (not name or name.lower().startswith(city.lower())):
        place = "SF Bay Area" if "san francisco" in city.lower() else city
        return f"Erlang Factory {place} {year}".strip() if place else (name or f"Erlang Factory {year}")
    if name:
        if year and str(year) not in name:
            return f"{name} ({year})"
        return name
    parts = [p for p in (city, str(year) if year else "") if p]
    return " ".join(parts) if parts else "Erlang Factory edition"


def yaml_escape(s):
    if s is None:
        return None
    s = str(s).replace('"', '\\"')
    return f'"{s}"'


def load_extraction():
    """slug -> extraction result from extract_erlang_factory.py, plus a
    url -> slug map. Empty if no extraction has run."""
    import sys
    sys.path.insert(0, str(ROOT / "migration-data"))
    try:
        from extract_erlang_factory import load_editions
        url2slug = {e["url"]: e["slug"] for e in load_editions()}
    except Exception:
        return {}, {}
    summary = ROOT / "older-conferences" / "_extract_summary.json"
    if not summary.exists():
        return {}, url2slug
    results = {r["slug"]: r for r in json.load(open(summary))}
    return results, url2slug


def edition_url(e, results, url2slug):
    """Prefer the locally extracted archive; fall back to Wayback for dead
    originals; keep the live URL otherwise. Returns (url, is_local)."""
    slug = url2slug.get(e.get("url"))
    r = results.get(slug) if slug else None
    if r and not r.get("error") and r.get("pages", 0) >= 1:
        return f"/older-conferences/{slug}/", True
    if e.get("live_status") != 200:  # dead original -> wayback, not a 403
        ts = (e.get("year") or 2012) + 1
        return f"https://web.archive.org/web/{ts}/{e['url']}", False
    return e.get("url"), False


def main():
    data = json.load(open(SRC))
    results, url2slug = load_extraction()
    groups = {b: [] for b in ORDER}
    for e in data:
        b = sub_brand(e)
        if b is None:
            continue
        groups[b].append(e)

    lines = ["# Generated by migration-data/build_older_conferences.py — do not edit by hand.",
             "# Pre-Sonata conference editions (erlang-factory.com era) for the",
             "# 'Older Conferences' section of /conferences/.",
             "# url is a local /older-conferences/<slug>/ archive when extracted",
             "# (local: true), else Wayback (dead originals) or the live site.", ""]
    total, n_local = 0, 0
    for b in ORDER:
        editions = groups[b]
        if not editions:
            continue
        # newest first; null year sorts last
        editions.sort(key=lambda e: (-(e.get("year") or 0), (e.get("name") or "")))
        lines.append(f"- brand: {yaml_escape(b)}")
        lines.append("  editions:")
        for e in editions:
            total += 1
            url, is_local = edition_url(e, results, url2slug)
            lines.append(f"    - label: {yaml_escape(edition_label(e, b))}")
            lines.append(f"      url: {yaml_escape(url)}")
            if is_local:
                n_local += 1
                lines.append("      local: true")
        lines.append("")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", "utf-8")
    print(f"wrote {OUT} — {total} editions across "
          f"{sum(1 for b in ORDER if groups[b])} sub-brands"
          f" ({n_local} local archives)")
    for b in ORDER:
        if groups[b]:
            print(f"  {b}: {len(groups[b])}")


if __name__ == "__main__":
    main()
